import type { Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Signalist",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ Server-side auth check
  const { userId } = auth();

  // If user is logged in, redirect before rendering
  if (userId) {
    redirect("/dashboard");
  }

  return (
    <ClerkProvider
      signInFallbackRedirectUrl="/dashboard"
      signUpFallbackRedirectUrl="/dashboard"
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="min-h-screen flex flex-col text-black">
            {/* Header */}
            <header className="flex justify-between items-center p-4">
              <h1 className="text-xl font-bold">Signalist</h1>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>

            {/* Main Content */}
            <main className="flex-1">
              <SignedOut>
                <div className="flex flex-col justify-center items-center h-screen gap-4">
                  <h2 className="text-2xl font-semibold mb-4">
                    Welcome to Signalist
                  </h2>
                  <SignInButton mode="modal">
                    <button className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                      Sign In / Sign Up
                    </button>
                  </SignInButton>
                </div>
              </SignedOut>
              <SignedIn>{children}</SignedIn>
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
